# Generated by Django 4.2.13 on 2024-07-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
