# Generated by Django 4.2.13 on 2024-07-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='memeber',
            new_name='member',
        ),
    ]
